<?php $signalData = $this->getSignalData(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Signal Lights</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
	<link rel="stylesheet" href="Skin/css/style.css">
</head>
<body>

<div class="container">
	<h1>Signal Lights Control</h1>

	<div class="signal-wrapper">
		<div class="signal-core">
			<div class="signal-circle red" id="circle-a"></div>
		</div>
		<div class="signal-core">
			<div class="signal-circle red" id="circle-b"></div>
		</div>
		<div class="signal-core">
			<div class="signal-circle red" id="circle-c"></div>
		</div>
		<div class="signal-core">
			<div class="signal-circle red" id="circle-d"></div>
		</div>
	</div>

	<form id="signal-form">
		<div class="signal-seq">
			<div class="form-group">
				<label for="signal-a">Signal A:</label>
				<input type="number" id="signal-a" name="signalA" min="1" max="4" value="<?php echo $signalData['a']; ?>" required>
			</div>

			<div class="form-group">
				<label for="signal-b">Signal B:</label>
				<input type="number" id="signal-b" name="signalB" min="1" max="4" value="<?php echo $signalData['b']; ?>" required>
			</div>

			<div class="form-group">
				<label for="signal-c">Signal C:</label>
				<input type="number" id="signal-c" name="signalC" min="1" max="4" value="<?php echo $signalData['c']; ?>" required>
			</div>

			<div class="form-group">
				<label for="signal-d">Signal D:</label>
				<input type="number" id="signal-d" name="signalD" min="1" max="4" value="<?php echo $signalData['d']; ?>" required>
			</div>
		</div>

		<div class="form-group">
			<label for="green-interval">Green Light Interval (sec):</label>
			<input type="number" id="green-interval" name="greenInterval" min="1" value="<?php echo $signalData['green_interval']; ?>" required>
		</div>

		<div class="form-group">
			<label for="yellow-interval">Yellow Light Interval (sec):</label>
			<input type="number" id="yellow-interval" name="yellowInterval" min="1" value="<?php echo $signalData['yellow_interval']; ?>" required>
		</div>

		<div class="buttons">
			<button type="button" onclick="startSignal()">Start</button>
			<button type="button" onclick="stopSignal(true)">Stop</button>
		</div>
	</form>
</div>

	<script type="text/javascript">
		function startSignal() {
			var a = $('#signal-a').val();
			var b = $('#signal-b').val();
			var c = $('#signal-c').val();
			var d = $('#signal-d').val();
			var greenInterval = $('#green-interval').val();
			var yellowInterval = $('#yellow-interval').val();
			$.ajax({
			 	type: "POST",
			 	data: {
			 		a: a,
			 		b: b,
			 		c: c,
			 		d: d,
			 		greenInterval: greenInterval,
			 		yellowInterval: yellowInterval
			 	},
			 	url: "<?php echo $this->getUrl('start') ?>", 
				success: function(response){
					response = JSON.parse(response);
					const sequence = [a, b, c, d];
					if (response.status === 'success') {
						runSignal(sequence, greenInterval, yellowInterval);
					}
					if (response.status === 'error') {
						alert(response.message)
					}
				}
			});
		}

		var signalTimeout;
		function runSignal(sequence, greenInterval, yellowInterval) {
			var	signalOrder = sequence.map(Number);
			var	currentSignal = 0;

			function changeSignalColor() {
				if (currentSignal >= signalOrder.length) {
					currentSignal = 0;
				}
				if (signalTimeout) {
					clearTimeout(signalTimeout);
					signalTimeout = null;
				}
				stopSignal()
				var id = signalOrder[currentSignal];
				var signalDiv = $('#circle-' + getSignalLatter(id))
				signalDiv.removeClass('red').addClass('green');
				signalTimeout = setTimeout(function() {
					signalDiv.removeClass('green').addClass('yellow');
					signalTimeout = setTimeout(function() {
						signalDiv.removeClass('yellow').addClass('red');
						currentSignal ++;
						changeSignalColor();
					}, yellowInterval * 1000);

				}, greenInterval * 1000);

			}
			changeSignalColor();
		}

		function stopSignal(button = false) {
			if (button) {
				$.ajax({
				 	type: "POST",
				 	data: {
				 	},
				 	url: "<?php echo $this->getUrl('stop') ?>", 
					success: function(response){
						response = JSON.parse(response);
						if (response.status === 'success') {
							console.log("signal stopped!!");
						}
					}
				});
			}
			clearTimeout(signalTimeout);
			signalTimeout = null;
			$('.signal-circle').removeClass('green yellow').addClass('red');
		}

		function getSignalLatter(id) {
			switch (id) {
				case 1:
					return 'a';
				case 2:
					return 'b';
				case 3:
					return 'c';
				case 4:
					return 'd';
				default:
					return ''
			}
		}
	</script>
</body>
</html>